services:
  - type: web
    name: prayer-tracker
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false  # This will be set manually in Render dashboard
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: prayer-tracker-db
    databaseName: prayertracker
    user: prayertracker
